version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: junior
      POSTGRES_DB: task_db

  your-spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: junior
      SPRING_APPLICATION_NAME: task
    depends_on:
      - postgres

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: myusername
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro